CREATE TABLE `CONFIG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONFIG_GROUP` varchar(100) DEFAULT NULL COMMENT '组',
  `CONFIG_KEY` varchar(100) DEFAULT NULL COMMENT '键',
  `CONFIG_VALUE` varchar(1000) DEFAULT NULL COMMENT '值',
  `REMARK` varchar(500) DEFAULT NULL COMMENT '备注',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `LAST_MODIF_TIME` datetime DEFAULT NULL COMMENT '最后修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `GROUP_KEY_UNIQUE` (`CONFIG_GROUP`,`CONFIG_KEY`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='系统配置表';

CREATE TABLE `demo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL COMMENT '用户名',
  `password` varchar(45) DEFAULT NULL COMMENT '密码',
  `icon` varchar(1024) DEFAULT NULL COMMENT '图标',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '状态',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index2` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=330 DEFAULT CHARSET=utf8;


